import { useState } from 'react'
import { Link, useParams } from '@tanstack/react-router'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, KeyRound, Layers3, Plus, ShieldCheck, Trash2, Users } from 'lucide-react'
import { toast } from 'sonner'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Header } from '@/components/layout/header'
import { Main } from '@/components/layout/main'
import { Search } from '@/components/search'
import { ThemeSwitch } from '@/components/theme-switch'
import { ConfirmDialog } from '@/components/confirm-dialog'
import { pondokApi, type Application } from '@/lib/pondok-api'

type Role = { id: string; code: string; name: string; description?: string | null }
type Permission = Role
type Member = { id: string; userId: string; username: string; displayName?: string | null; email?: string | null; status: string }
type User = { id: string; localId?: string | null; username: string; displayName?: string | null; email?: string | null }
type Admin = { userId: string; username: string; displayName?: string | null; email?: string | null }
type OAuthClient = { id: string; clientId: string; name: string; clientType: string; enabled: boolean; redirectUris?: string[]; webOrigins?: string[] }

const emptyNameForm = { code: '', name: '', description: '' }
const emptyClientForm = { clientId: '', name: '', clientType: 'web', redirectUris: '', webOrigins: '' }

export function ApplicationDetail() {
  const { applicationId } = useParams({ from: '/_authenticated/applications/$applicationId' })
  const queryClient = useQueryClient()
  const [roleDialog, setRoleDialog] = useState(false)
  const [permissionDialog, setPermissionDialog] = useState(false)
  const [memberDialog, setMemberDialog] = useState(false)
  const [adminDialog, setAdminDialog] = useState(false)
  const [clientDialog, setClientDialog] = useState(false)
  const [assignmentDialog, setAssignmentDialog] = useState<{ kind: 'role' | 'permission'; id: string } | null>(null)
  const [roleForm, setRoleForm] = useState(emptyNameForm)
  const [permissionForm, setPermissionForm] = useState(emptyNameForm)
  const [memberForm, setMemberForm] = useState({ userId: '', status: 'active' })
  const [adminUserId, setAdminUserId] = useState('')
  const [clientForm, setClientForm] = useState(emptyClientForm)
  const [assignmentId, setAssignmentId] = useState('')
  const [secret, setSecret] = useState<string | null>(null)
  const [confirming, setConfirming] = useState<{ path: string; label: string } | null>(null)

  const invalidate = () => {
    for (const key of ['application-roles', 'application-permissions', 'application-members', 'application-clients']) queryClient.invalidateQueries({ queryKey: [key, applicationId] })
  }
  const mutation = (path: string, body?: unknown, method = 'POST') => pondokApi(path, { method, body: body === undefined ? undefined : JSON.stringify(body) })
  const createRole = useMutation({ mutationFn: () => mutation(`/api/applications/${applicationId}/roles`, roleForm), onSuccess: () => { invalidate(); setRoleDialog(false); setRoleForm(emptyNameForm); toast.success('Role created') }, onError: () => toast.error('Unable to create role') })
  const createPermission = useMutation({ mutationFn: () => mutation(`/api/applications/${applicationId}/permissions`, permissionForm), onSuccess: () => { invalidate(); setPermissionDialog(false); setPermissionForm(emptyNameForm); toast.success('Permission created') }, onError: () => toast.error('Unable to create permission') })
  const addMember = useMutation({ mutationFn: () => mutation(`/api/applications/${applicationId}/members`, memberForm), onSuccess: () => { invalidate(); setMemberDialog(false); setMemberForm({ userId: '', status: 'active' }); toast.success('Member added') }, onError: () => toast.error('Unable to add member') })
  const addAdmin = useMutation({ mutationFn: () => mutation(`/api/applications/${applicationId}/admins`, { id: adminUserId }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['application-admins', applicationId] }); setAdminDialog(false); setAdminUserId(''); toast.success('Application admin assigned') }, onError: () => toast.error('Unable to assign application admin') })
  const addClient = useMutation({ mutationFn: () => mutation(`/api/applications/${applicationId}/oauth-clients`, { ...clientForm, redirectUris: clientForm.redirectUris.split(',').map((item) => item.trim()).filter(Boolean), webOrigins: clientForm.webOrigins.split(',').map((item) => item.trim()).filter(Boolean) }), onSuccess: () => { invalidate(); setClientDialog(false); setClientForm(emptyClientForm); toast.success('OAuth client created') }, onError: () => toast.error('Unable to create OAuth client') })
  const remove = useMutation({ mutationFn: ({ path }: { path: string }) => mutation(path, undefined, 'DELETE'), onSuccess: () => { invalidate(); queryClient.invalidateQueries({ queryKey: ['application-admins', applicationId] }); setConfirming(null); toast.success('Resource removed') }, onError: () => toast.error('Unable to remove resource') })
  const toggleMember = useMutation({ mutationFn: ({ member, status }: { member: Member; status: string }) => mutation(`/api/applications/${applicationId}/members/${member.id}`, { status }, 'PATCH'), onSuccess: invalidate, onError: () => toast.error('Unable to update member') })
  const assign = useMutation({ mutationFn: () => { if (!assignmentDialog) throw new Error('No assignment selected'); const path = assignmentDialog.kind === 'role' ? `/api/applications/${applicationId}/members/${assignmentDialog.id}/roles` : `/api/applications/${applicationId}/roles/${assignmentDialog.id}/permissions`; return mutation(path, { id: assignmentId }) }, onSuccess: () => { setAssignmentDialog(null); setAssignmentId(''); toast.success('Assignment saved') }, onError: () => toast.error('Unable to save assignment') })
  const rotateSecret = useMutation({ mutationFn: (clientId: string) => pondokApi<{ secret: string }>(`/api/applications/${applicationId}/oauth-clients/${clientId}/rotate-secret`, { method: 'POST' }), onSuccess: (result) => { setSecret(result.secret); toast.success('Secret rotated. Copy it now; it will not be shown again.') }, onError: () => toast.error('Unable to rotate client secret') })

  const application = useQuery({ queryKey: ['application', applicationId], queryFn: async () => (await pondokApi<Application[]>('/api/applications')).find((item) => item.id === applicationId) })
  const roles = useQuery({ queryKey: ['application-roles', applicationId], queryFn: () => pondokApi<Role[]>(`/api/applications/${applicationId}/roles`) })
  const permissions = useQuery({ queryKey: ['application-permissions', applicationId], queryFn: () => pondokApi<Permission[]>(`/api/applications/${applicationId}/permissions`) })
  const members = useQuery({ queryKey: ['application-members', applicationId], queryFn: () => pondokApi<Member[]>(`/api/applications/${applicationId}/members`) })
  const clients = useQuery({ queryKey: ['application-clients', applicationId], queryFn: () => pondokApi<OAuthClient[]>(`/api/applications/${applicationId}/oauth-clients`) })
  const users = useQuery({ queryKey: ['application-user-directory', applicationId], queryFn: () => pondokApi<User[]>(`/api/applications/${applicationId}/user-directory`) })
  const me = useQuery({ queryKey: ['me'], queryFn: () => pondokApi<{ user: { realmRoles: string[]; clientRoles: string[] } | null }>('/api/me') })
  const canManageAdmins = Boolean(me.data?.user?.realmRoles.includes('platform-admin') || me.data?.user?.clientRoles.includes('platform-admin'))
  const admins = useQuery({ queryKey: ['application-admins', applicationId], queryFn: () => pondokApi<Admin[]>(`/api/applications/${applicationId}/admins`), enabled: canManageAdmins })
  const loading = application.isLoading

  if (loading) return <><Header><Search /><ThemeSwitch /></Header><Main><p className='py-10 text-center text-sm text-muted-foreground'>Loading application…</p></Main></>
  if (!application.data) return <><Header><Search /><ThemeSwitch /></Header><Main><p className='py-10 text-center text-sm text-destructive'>Application not found.</p></Main></>

  const app = application.data
  return <><Header><Search /><ThemeSwitch /></Header><Main>
    <Button asChild variant='ghost' className='mb-4 -ms-3'><Link to='/applications'><ArrowLeft className='me-2 size-4' />Back to applications</Link></Button>
    <div className='mb-6 flex flex-wrap items-start justify-between gap-4'><div><div className='mb-2 flex items-center gap-2'><Badge>{app.code}</Badge><Badge variant='outline'>{app.status}</Badge></div><h1 className='text-2xl font-bold tracking-tight'>{app.name}</h1><p className='mt-1 text-muted-foreground'>{app.description || 'No description provided.'}</p></div><div className='flex gap-2'>{canManageAdmins && <Button variant='outline' onClick={() => setAdminDialog(true)}>Manage admins</Button>}<Button onClick={() => setClientDialog(true)}><Plus className='me-2 size-4' />Add OAuth client</Button></div></div>
    <div className='mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4'>{[{ label: 'OAuth clients', value: clients.data?.length, icon: KeyRound }, { label: 'Members', value: members.data?.length, icon: Users }, { label: 'Roles', value: roles.data?.length, icon: ShieldCheck }, { label: 'Permissions', value: permissions.data?.length, icon: Layers3 }].map(({ label, value, icon: Icon }) => <Card key={label}><CardHeader className='flex flex-row items-center justify-between pb-2'><CardTitle className='text-sm font-medium'>{label}</CardTitle><Icon className='size-4 text-muted-foreground' /></CardHeader><CardContent><div className='text-2xl font-bold'>{value ?? '—'}</div></CardContent></Card>)}</div>
    {secret && <Card className='mb-4 border-amber-500'><CardHeader><CardTitle>New client secret</CardTitle><CardDescription>Copy this secret now. It is not stored or displayed again.</CardDescription></CardHeader><CardContent><code className='break-all rounded bg-muted p-2 text-sm'>{secret}</code><Button className='ms-3' size='sm' onClick={() => navigator.clipboard.writeText(secret)}>Copy</Button></CardContent></Card>}
    {[roles, permissions, members, clients].some((query) => query.isError) && <div className='mb-4 rounded-md border border-destructive/50 bg-destructive/5 p-3 text-sm text-destructive'>Some application resources could not be loaded. Refresh the page and try again.</div>}
    <Tabs defaultValue='clients'><TabsList><TabsTrigger value='clients'>OAuth clients</TabsTrigger><TabsTrigger value='members'>Members</TabsTrigger><TabsTrigger value='roles'>Roles</TabsTrigger><TabsTrigger value='permissions'>Permissions</TabsTrigger></TabsList>
      <TabsContent value='clients'><ResourceCard title='OAuth clients' description='Clients connected to this application.' action={<Button size='sm' onClick={() => setClientDialog(true)}><Plus className='me-1 size-4' />Add</Button>}>{clients.data?.length ? <div className='divide-y rounded-md border'>{clients.data.map((client) => <div className='flex flex-wrap items-center justify-between gap-3 p-3 text-sm' key={client.id}><div><div className='font-medium'>{client.name}</div><div className='text-muted-foreground'>{client.clientId} · {client.clientType} · {client.enabled ? 'Enabled' : 'Disabled'}</div></div><div className='flex gap-2'><Button size='sm' variant='outline' onClick={() => rotateSecret.mutate(client.id)}>Rotate secret</Button><Button size='sm' variant='ghost' className='text-destructive' onClick={() => setConfirming({ path: `/api/applications/${applicationId}/oauth-clients/${client.id}`, label: `OAuth client ${client.name}` })}><Trash2 className='size-4' /></Button></div></div>)}</div> : <Empty text='No OAuth clients configured.' />}</ResourceCard></TabsContent>
      <TabsContent value='members'><ResourceCard title='Members' description='Users with access to this application.' action={<Button size='sm' onClick={() => setMemberDialog(true)}><Plus className='me-1 size-4' />Add</Button>}>{members.data?.length ? <div className='divide-y rounded-md border'>{members.data.map((member) => <div className='flex flex-wrap items-center justify-between gap-3 p-3 text-sm' key={member.id}><div><div className='font-medium'>{member.displayName || member.username}</div><div className='text-muted-foreground'>{member.email || member.username} · {member.status}</div></div><div className='flex gap-2'><Button size='sm' variant='outline' onClick={() => { setAssignmentDialog({ kind: 'role', id: member.id }); setAssignmentId('') }}>Assign role</Button><Button size='sm' variant='ghost' onClick={() => toggleMember.mutate({ member, status: member.status === 'active' ? 'disabled' : 'active' })}>{member.status === 'active' ? 'Disable' : 'Enable'}</Button><Button size='sm' variant='ghost' className='text-destructive' onClick={() => setConfirming({ path: `/api/applications/${applicationId}/members/${member.id}`, label: `membership for ${member.username}` })}><Trash2 className='size-4' /></Button></div></div>)}</div> : <Empty text='No members assigned.' />}</ResourceCard></TabsContent>
      <TabsContent value='roles'><ResourceCard title='Roles' description='Application roles synchronized to Keycloak client roles.' action={<Button size='sm' onClick={() => setRoleDialog(true)}><Plus className='me-1 size-4' />Add</Button>}>{roles.data?.length ? <div className='divide-y rounded-md border'>{roles.data.map((role) => <div className='flex flex-wrap items-center justify-between gap-3 p-3 text-sm' key={role.id}><div><div className='font-medium'>{role.name}</div><div className='text-muted-foreground'>{role.code}{role.description ? ` · ${role.description}` : ''}</div></div><div className='flex gap-2'><Button size='sm' variant='outline' onClick={() => { setAssignmentDialog({ kind: 'permission', id: role.id }); setAssignmentId('') }}>Add permission</Button><Button size='sm' variant='ghost' className='text-destructive' onClick={() => setConfirming({ path: `/api/applications/${applicationId}/roles/${role.id}`, label: `role ${role.name}` })}><Trash2 className='size-4' /></Button></div></div>)}</div> : <Empty text='No roles configured.' />}</ResourceCard></TabsContent>
      <TabsContent value='permissions'><ResourceCard title='Permissions' description='Fine-grained permissions for delegated administration.' action={<Button size='sm' onClick={() => setPermissionDialog(true)}><Plus className='me-1 size-4' />Add</Button>}>{permissions.data?.length ? <div className='divide-y rounded-md border'>{permissions.data.map((permission) => <div className='flex items-center justify-between gap-3 p-3 text-sm' key={permission.id}><div><div className='font-medium'>{permission.name}</div><div className='text-muted-foreground'>{permission.code}</div></div><Button size='sm' variant='ghost' className='text-destructive' onClick={() => setConfirming({ path: `/api/applications/${applicationId}/permissions/${permission.id}`, label: `permission ${permission.name}` })}><Trash2 className='size-4' /></Button></div>)}</div> : <Empty text='No permissions configured.' />}</ResourceCard></TabsContent>
    </Tabs>
    {canManageAdmins && <ResourceCard title='Application administrators' description='Platform administrators who can manage this application.' action={<Button size='sm' onClick={() => setAdminDialog(true)}><Plus className='me-1 size-4' />Add</Button>}>{admins.data?.length ? <div className='divide-y rounded-md border'>{admins.data.map((admin) => <div className='flex items-center justify-between gap-3 p-3 text-sm' key={admin.userId}><div><div className='font-medium'>{admin.displayName || admin.username}</div><div className='text-muted-foreground'>{admin.email || admin.username}</div></div><Button size='sm' variant='ghost' className='text-destructive' onClick={() => setConfirming({ path: `/api/applications/${applicationId}/admins/${admin.userId}`, label: `administrator ${admin.username}` })}><Trash2 className='size-4' /></Button></div>)}</div> : <Empty text='No delegated administrators configured.' />}</ResourceCard>}
  </Main>
  <ConfirmDialog open={Boolean(confirming)} onOpenChange={(open) => !open && setConfirming(null)} title={`Remove ${confirming?.label}?`} desc='This action cannot be undone and may revoke access in Keycloak.' destructive confirmText={remove.isPending ? 'Removing…' : 'Remove'} isLoading={remove.isPending} handleConfirm={() => confirming && remove.mutate({ path: confirming.path })} />
  <Dialog open={roleDialog} onOpenChange={setRoleDialog}><DialogContent><DialogHeader><DialogTitle>Create role</DialogTitle><DialogDescription>The role is synchronized to every OAuth client of this application.</DialogDescription></DialogHeader><NameForm form={roleForm} setForm={setRoleForm} prefix='role' /><DialogFooter><Button variant='outline' onClick={() => setRoleDialog(false)}>Cancel</Button><Button onClick={() => createRole.mutate()} disabled={createRole.isPending}>Create role</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={permissionDialog} onOpenChange={setPermissionDialog}><DialogContent><DialogHeader><DialogTitle>Create permission</DialogTitle></DialogHeader><NameForm form={permissionForm} setForm={setPermissionForm} prefix='permission' /><DialogFooter><Button variant='outline' onClick={() => setPermissionDialog(false)}>Cancel</Button><Button onClick={() => createPermission.mutate()} disabled={createPermission.isPending}>Create permission</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={memberDialog} onOpenChange={setMemberDialog}><DialogContent><DialogHeader><DialogTitle>Add member</DialogTitle><DialogDescription>Only users already present in the Pondok directory can be added.</DialogDescription></DialogHeader><Label htmlFor='member-user'>User</Label><select id='member-user' className='h-9 rounded-md border bg-background px-3 text-sm' value={memberForm.userId} onChange={(event) => setMemberForm({ ...memberForm, userId: event.target.value })}><option value=''>Select user</option>{users.data?.filter((user) => user.localId).map((user) => <option key={user.localId} value={user.localId!}>{user.displayName || user.username} ({user.username})</option>)}</select><DialogFooter><Button variant='outline' onClick={() => setMemberDialog(false)}>Cancel</Button><Button onClick={() => addMember.mutate()} disabled={!memberForm.userId || addMember.isPending}>Add member</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={adminDialog} onOpenChange={setAdminDialog}><DialogContent><DialogHeader><DialogTitle>Assign application administrator</DialogTitle><DialogDescription>Only platform administrators can change this list.</DialogDescription></DialogHeader><Label htmlFor='admin-user'>User</Label><select id='admin-user' className='h-9 rounded-md border bg-background px-3 text-sm' value={adminUserId} onChange={(event) => setAdminUserId(event.target.value)}><option value=''>Select user</option>{users.data?.filter((user) => user.localId).map((user) => <option key={user.localId} value={user.localId!}>{user.displayName || user.username} ({user.username})</option>)}</select><DialogFooter><Button variant='outline' onClick={() => setAdminDialog(false)}>Cancel</Button><Button onClick={() => addAdmin.mutate()} disabled={!adminUserId || addAdmin.isPending}>Assign admin</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={clientDialog} onOpenChange={setClientDialog}><DialogContent><DialogHeader><DialogTitle>Create OAuth client</DialogTitle><DialogDescription>Redirect URIs and web origins are comma-separated.</DialogDescription></DialogHeader><div className='grid gap-3'><Field label='Client ID' value={clientForm.clientId} onChange={(value) => setClientForm({ ...clientForm, clientId: value })} /><Field label='Name' value={clientForm.name} onChange={(value) => setClientForm({ ...clientForm, name: value })} /><div className='grid gap-2'><Label htmlFor='client-type'>Client type</Label><select id='client-type' className='h-9 rounded-md border bg-background px-3 text-sm' value={clientForm.clientType} onChange={(event) => setClientForm({ ...clientForm, clientType: event.target.value })}>{['web', 'api', 'mobile', 'service'].map((type) => <option key={type}>{type}</option>)}</select></div><Field label='Redirect URIs' value={clientForm.redirectUris} onChange={(value) => setClientForm({ ...clientForm, redirectUris: value })} /><Field label='Web origins' value={clientForm.webOrigins} onChange={(value) => setClientForm({ ...clientForm, webOrigins: value })} /></div><DialogFooter><Button variant='outline' onClick={() => setClientDialog(false)}>Cancel</Button><Button onClick={() => addClient.mutate()} disabled={addClient.isPending}>Create client</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={Boolean(assignmentDialog)} onOpenChange={(open) => !open && setAssignmentDialog(null)}><DialogContent><DialogHeader><DialogTitle>{assignmentDialog?.kind === 'role' ? 'Assign role to member' : 'Attach permission to role'}</DialogTitle></DialogHeader><select className='h-9 rounded-md border bg-background px-3 text-sm' value={assignmentId} onChange={(event) => setAssignmentId(event.target.value)}><option value=''>Select {assignmentDialog?.kind === 'role' ? 'role' : 'permission'}</option>{(assignmentDialog?.kind === 'role' ? roles.data : permissions.data)?.map((item) => <option key={item.id} value={item.id}>{item.name} ({item.code})</option>)}</select><DialogFooter><Button variant='outline' onClick={() => setAssignmentDialog(null)}>Cancel</Button><Button onClick={() => assign.mutate()} disabled={!assignmentId || assign.isPending}>Save assignment</Button></DialogFooter></DialogContent></Dialog>
  </>
}

function ResourceCard({ title, description, action, children }: { title: string; description: string; action: React.ReactNode; children: React.ReactNode }) { return <Card className='mt-4'><CardHeader className='flex flex-row items-start justify-between gap-3'><div><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></div>{action}</CardHeader><CardContent>{children}</CardContent></Card> }
function Empty({ text }: { text: string }) { return <p className='py-6 text-sm text-muted-foreground'>{text}</p> }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { const id = label.toLowerCase().replace(/ /g, '-'); return <div className='grid gap-2'><Label htmlFor={id}>{label}</Label><Input id={id} value={value} onChange={(event) => onChange(event.target.value)} required /></div> }
function NameForm({ form, setForm, prefix }: { form: typeof emptyNameForm; setForm: (value: typeof emptyNameForm) => void; prefix: string }) { return <div className='grid gap-3'><Field label={`${prefix} code`} value={form.code} onChange={(value) => setForm({ ...form, code: value })} /><Field label='Name' value={form.name} onChange={(value) => setForm({ ...form, name: value })} /><Field label='Description' value={form.description} onChange={(value) => setForm({ ...form, description: value })} /></div> }
