import { BadRequestException, Body, Controller, Delete, ForbiddenException, Get, NotFoundException, Param, Patch, Post, Req, UseGuards } from '@nestjs/common';
import { and, desc, eq, ilike } from 'drizzle-orm';
import { db } from '../db/database';
import { applicationAdmins, applicationMemberships, applicationOauthClients, applications, auditLogs, membershipRoles, permissions, rolePermissions, roles, users } from '../db/schema';
import { SessionGuard, PlatformAdminGuard } from '../auth/guards';
import { ApplicationDto, ApplicationUpdateDto, AssignmentDto, MembershipCreateDto, MembershipUpdateDto, OAuthClientDto, OAuthClientUpdateDto, PermissionDto, RoleDto } from './dto';
import { KeycloakService } from '../keycloak/keycloak.service';

@Controller('api/applications')
@UseGuards(SessionGuard)
export class ApplicationsController {
  constructor(private readonly keycloak: KeycloakService) {}
  private async audit(req: any, action: string, entityType: string, entityId: string | undefined, metadata: unknown = {}) { await db.insert(auditLogs).values({ actorUserId: req.session.user.id, action, entityType, entityId, metadata }); }
  private async assertApplication(id: string) { const rows = await db.select().from(applications).where(eq(applications.id, id)); if (!rows[0]) throw new NotFoundException('Application not found'); return rows[0]; }
  private async assertManageAccess(id: string, req: any) { const user = req.session.user; if (user.realmRoles?.includes('platform-admin') || user.clientRoles?.includes('platform-admin')) return; const rows = await db.select().from(applicationAdmins).where(and(eq(applicationAdmins.applicationId, id), eq(applicationAdmins.userId, user.id))); if (!rows[0]) throw new ForbiddenException('Application administrator access required'); }
  private async syncMembershipRoles(applicationId: string, membershipId: string, keycloakUserId: string, assign: boolean) { const assigned = await db.select().from(membershipRoles).innerJoin(roles, eq(roles.id, membershipRoles.roleId)).where(eq(membershipRoles.membershipId, membershipId)); const clients = await db.select().from(applicationOauthClients).where(eq(applicationOauthClients.applicationId, applicationId)); for (const row of assigned) for (const client of clients) { if (assign) await this.keycloak.assignClientRole(keycloakUserId, client.keycloakClientUuid, row.roles.code); else await this.keycloak.removeClientRole(keycloakUserId, client.keycloakClientUuid, row.roles.code); } }
  @Get() list(@Req() req: any) { const user = req.session.user; const search = req.query.search ? ilike(applications.name, `%${req.query.search}%`) : undefined; if (user.realmRoles?.includes('platform-admin') || user.clientRoles?.includes('platform-admin')) return db.select().from(applications).where(search).orderBy(applications.code); return db.select({ id: applications.id, code: applications.code, name: applications.name, description: applications.description, status: applications.status }).from(applications).innerJoin(applicationAdmins, eq(applicationAdmins.applicationId, applications.id)).where(search ? and(eq(applicationAdmins.userId, user.id), search) : eq(applicationAdmins.userId, user.id)); }
  @Post() @UseGuards(PlatformAdminGuard) async create(@Body() body: ApplicationDto, @Req() req: any) { const result = await db.insert(applications).values(body).returning(); await this.audit(req, 'create', 'application', result[0].id, body); return result[0]; }
  @Patch(':id') @UseGuards(PlatformAdminGuard) async update(@Param('id') id: string, @Body() body: ApplicationUpdateDto, @Req() req: any) { await this.assertApplication(id); const result = await db.update(applications).set({ ...body, updatedAt: new Date() }).where(eq(applications.id, id)).returning(); await this.audit(req, 'application.updated', 'application', id, body); return result[0]; }
  @Delete(':id') @UseGuards(PlatformAdminGuard) async remove(@Param('id') id: string, @Req() req: any) { await this.assertApplication(id); const clients = await db.select().from(applicationOauthClients).where(eq(applicationOauthClients.applicationId, id)); try { for (const client of clients) await this.keycloak.deleteClient(client.keycloakClientUuid); } catch { throw new BadRequestException('Unable to remove all Keycloak clients for this application'); } await db.delete(applications).where(eq(applications.id, id)); await this.audit(req, 'delete', 'application', id); return { deleted: true }; }
  @Get(':id/user-directory') async userDirectory(@Param('id') id: string, @Req() req: any) { await this.assertManageAccess(id, req); return db.select({ localId: users.id, username: users.username, displayName: users.displayName, email: users.email, status: users.status }).from(users).orderBy(users.username); }
  @Get(':id/roles') async roleList(@Param('id') id: string, @Req() req: any) { await this.assertManageAccess(id, req); return db.select().from(roles).where(eq(roles.applicationId, id)).orderBy(roles.code); }
  @Post(':id/roles') async createRole(@Param('id') id: string, @Body() body: RoleDto, @Req() req: any) { await this.assertManageAccess(id, req); const result = await db.insert(roles).values({ applicationId: id, ...body }).returning(); try { const clients = await db.select().from(applicationOauthClients).where(eq(applicationOauthClients.applicationId, id)); for (const client of clients) await this.keycloak.ensureClientRole(client.keycloakClientUuid, body.code); await this.audit(req, 'create', 'role', result[0].id, body); return result[0]; } catch (error) { await db.delete(roles).where(eq(roles.id, result[0].id)).catch(() => undefined); throw new BadRequestException('Unable to synchronize the role with Keycloak'); } }
  @Delete(':id/roles/:roleId') async removeRole(@Param('id') id: string, @Param('roleId') roleId: string, @Req() req: any) { await this.assertManageAccess(id, req); const rows = await db.select().from(roles).where(and(eq(roles.id, roleId), eq(roles.applicationId, id))); const role = rows[0]; if (!role) throw new NotFoundException('Role not found'); const clients = await db.select().from(applicationOauthClients).where(eq(applicationOauthClients.applicationId, id)); try { for (const client of clients) await this.keycloak.deleteClientRole(client.keycloakClientUuid, role.code); } catch { throw new BadRequestException('Unable to remove the role from all Keycloak clients'); } await db.delete(roles).where(eq(roles.id, roleId)); await this.audit(req, 'role.deleted', 'role', roleId); return { deleted: true }; }
  @Get(':id/permissions') async permissionList(@Param('id') id: string, @Req() req: any) { await this.assertManageAccess(id, req); return db.select().from(permissions).where(eq(permissions.applicationId, id)).orderBy(permissions.code); }
  @Post(':id/permissions') async createPermission(@Param('id') id: string, @Body() body: PermissionDto, @Req() req: any) { await this.assertManageAccess(id, req); const result = await db.insert(permissions).values({ applicationId: id, ...body }).returning(); await this.audit(req, 'create', 'permission', result[0].id, body); return result[0]; }
  @Delete(':id/permissions/:permissionId') async removePermission(@Param('id') id: string, @Param('permissionId') permissionId: string, @Req() req: any) { await this.assertManageAccess(id, req); const rows = await db.delete(permissions).where(and(eq(permissions.id, permissionId), eq(permissions.applicationId, id))).returning(); if (!rows[0]) throw new NotFoundException('Permission not found'); await this.audit(req, 'delete', 'permission', permissionId); return { deleted: true }; }
  @Post(':id/roles/:roleId/permissions') async attachPermission(@Param('id') id: string, @Param('roleId') roleId: string, @Body() body: AssignmentDto, @Req() req: any) { await this.assertManageAccess(id, req); await db.transaction(async (tx) => { const role = (await tx.select().from(roles).where(and(eq(roles.id, roleId), eq(roles.applicationId, id))))[0]; const permission = (await tx.select().from(permissions).where(and(eq(permissions.id, body.id), eq(permissions.applicationId, id))))[0]; if (!role || !permission) throw new BadRequestException('Role and permission must belong to the same application'); await tx.insert(rolePermissions).values({ roleId, permissionId: body.id }).onConflictDoNothing(); }); await this.audit(req, 'assign', 'role_permission', `${roleId}:${body.id}`); return { assigned: true }; }
  @Get(':id/roles/:roleId/permissions') async rolePermissionList(@Param('id') id: string, @Param('roleId') roleId: string, @Req() req: any) { await this.assertManageAccess(id, req); return db.select().from(rolePermissions).where(eq(rolePermissions.roleId, roleId)); }
  @Delete(':id/roles/:roleId/permissions/:permissionId') async detachPermission(@Param('id') id: string, @Param('roleId') roleId: string, @Param('permissionId') permissionId: string, @Req() req: any) { await this.assertManageAccess(id, req); await db.delete(rolePermissions).where(and(eq(rolePermissions.roleId, roleId), eq(rolePermissions.permissionId, permissionId))); await this.audit(req, 'unassign', 'role_permission', `${roleId}:${permissionId}`); return { deleted: true }; }
  @Get(':id/members') async memberList(@Param('id') id: string, @Req() req: any) { await this.assertManageAccess(id, req); return db.select({ id: applicationMemberships.id, userId: users.id, username: users.username, displayName: users.displayName, email: users.email, status: applicationMemberships.status, createdAt: applicationMemberships.createdAt }).from(applicationMemberships).innerJoin(users, eq(users.id, applicationMemberships.userId)).where(eq(applicationMemberships.applicationId, id)).orderBy(desc(applicationMemberships.createdAt)); }
  @Post(':id/members') async addMember(@Param('id') id: string, @Body() body: MembershipCreateDto, @Req() req: any) { await this.assertManageAccess(id, req); const user = (await db.select().from(users).where(eq(users.id, body.userId)))[0]; if (!user) throw new BadRequestException('User not found'); const result = await db.insert(applicationMemberships).values({ applicationId: id, userId: body.userId, status: body.status || 'active' }).returning(); await this.audit(req, 'membership.created', 'membership', result[0].id, body); return result[0]; }
  @Patch(':id/members/:membershipId') async updateMember(@Param('id') id: string, @Param('membershipId') membershipId: string, @Body() body: MembershipUpdateDto, @Req() req: any) { await this.assertManageAccess(id, req); const current = (await db.select().from(applicationMemberships).innerJoin(users, eq(users.id, applicationMemberships.userId)).where(and(eq(applicationMemberships.id, membershipId), eq(applicationMemberships.applicationId, id))))[0]; if (!current) throw new NotFoundException('Membership not found'); const result = (await db.update(applicationMemberships).set({ status: body.status, updatedAt: new Date() }).where(eq(applicationMemberships.id, membershipId)).returning())[0]; try { await this.syncMembershipRoles(id, membershipId, current.users.keycloakUserId, body.status !== 'disabled'); } catch { await db.update(applicationMemberships).set({ status: current.application_memberships.status, updatedAt: new Date() }).where(eq(applicationMemberships.id, membershipId)); throw new BadRequestException('Unable to synchronize membership access with Keycloak'); } await this.audit(req, 'membership.updated', 'membership', membershipId, body); return result; }
  @Delete(':id/members/:membershipId') async removeMember(@Param('id') id: string, @Param('membershipId') membershipId: string, @Req() req: any) { await this.assertManageAccess(id, req); const current = (await db.select().from(applicationMemberships).innerJoin(users, eq(users.id, applicationMemberships.userId)).where(and(eq(applicationMemberships.id, membershipId), eq(applicationMemberships.applicationId, id))))[0]; if (!current) throw new NotFoundException('Membership not found'); try { await this.syncMembershipRoles(id, membershipId, current.users.keycloakUserId, false); } catch { throw new BadRequestException('Unable to revoke membership access from Keycloak'); } await db.delete(applicationMemberships).where(eq(applicationMemberships.id, membershipId)); await this.audit(req, 'membership.deleted', 'membership', membershipId); return { deleted: true }; }
  @Get(':id/members/:membershipId/roles') async memberRoleList(@Param('id') id: string, @Param('membershipId') membershipId: string, @Req() req: any) { await this.assertManageAccess(id, req); return db.select().from(membershipRoles).where(eq(membershipRoles.membershipId, membershipId)); }
  @Post(':id/members/:membershipId/roles') async attachMemberRole(@Param('id') id: string, @Param('membershipId') membershipId: string, @Body() body: AssignmentDto, @Req() req: any) { await this.assertManageAccess(id, req); const member = (await db.select().from(applicationMemberships).innerJoin(users, eq(users.id, applicationMemberships.userId)).where(and(eq(applicationMemberships.id, membershipId), eq(applicationMemberships.applicationId, id))))[0]; const role = (await db.select().from(roles).where(and(eq(roles.id, body.id), eq(roles.applicationId, id))))[0]; if (!member || !role) throw new BadRequestException('Membership and role must belong to the same application'); const clients = await db.select().from(applicationOauthClients).where(eq(applicationOauthClients.applicationId, id)); try { for (const client of clients) await this.keycloak.assignClientRole(member.users.keycloakUserId, client.keycloakClientUuid, role.code); await db.insert(membershipRoles).values({ membershipId, roleId: body.id, assignedBy: req.session.user.id }).onConflictDoNothing(); } catch (error) { throw new BadRequestException('Unable to synchronize the role assignment with Keycloak'); } await this.audit(req, 'assign', 'membership_role', `${membershipId}:${body.id}`); return { assigned: true }; }
  @Delete(':id/members/:membershipId/roles/:roleId') async detachMemberRole(@Param('id') id: string, @Param('membershipId') membershipId: string, @Param('roleId') roleId: string, @Req() req: any) { await this.assertManageAccess(id, req); const assignment = (await db.select().from(membershipRoles).innerJoin(applicationMemberships, eq(applicationMemberships.id, membershipRoles.membershipId)).innerJoin(users, eq(users.id, applicationMemberships.userId)).innerJoin(roles, eq(roles.id, membershipRoles.roleId)).where(and(eq(membershipRoles.membershipId, membershipId), eq(membershipRoles.roleId, roleId), eq(applicationMemberships.applicationId, id))))[0]; if (!assignment) throw new NotFoundException('Membership role assignment not found'); const clients = await db.select().from(applicationOauthClients).where(eq(applicationOauthClients.applicationId, id)); try { for (const client of clients) await this.keycloak.removeClientRole(assignment.users.keycloakUserId, client.keycloakClientUuid, assignment.roles.code); } catch (error) { throw new BadRequestException('Unable to synchronize the role removal with Keycloak'); } await db.delete(membershipRoles).where(and(eq(membershipRoles.membershipId, membershipId), eq(membershipRoles.roleId, roleId))); await this.audit(req, 'membership_role.deleted', 'membership_role', `${membershipId}:${roleId}`); return { deleted: true }; }
  @Get(':id/oauth-clients') async clientList(@Param('id') id: string, @Req() req: any) { await this.assertManageAccess(id, req); return db.select().from(applicationOauthClients).where(eq(applicationOauthClients.applicationId, id)); }
  @Post(':id/oauth-clients') async createClient(@Param('id') id: string, @Body() body: OAuthClientDto, @Req() req: any) { await this.assertManageAccess(id, req); const enabled = body.enabled !== false; const redirectUris = body.redirectUris || []; const webOrigins = body.webOrigins || []; const kcClient: any = await this.keycloak.createClient({ clientId: body.clientId, name: body.name, enabled, protocol: 'openid-connect', publicClient: body.clientType === 'mobile', standardFlowEnabled: body.clientType === 'web' || body.clientType === 'mobile', directAccessGrantsEnabled: false, serviceAccountsEnabled: body.clientType === 'service', redirectUris, webOrigins }); const found = kcClient?.id ? kcClient : await this.keycloak.findClient(body.clientId); if (!found?.id) throw new BadRequestException('Keycloak client was not created'); let localClientId: string | undefined; try { const result = await db.insert(applicationOauthClients).values({ applicationId: id, keycloakClientUuid: found.id, clientId: body.clientId, clientType: body.clientType, name: body.name, enabled, redirectUris, webOrigins }).returning(); localClientId = result[0].id; const appRoles = await db.select().from(roles).where(eq(roles.applicationId, id)); for (const role of appRoles) await this.keycloak.ensureClientRole(found.id, role.code); const memberships = await db.select().from(applicationMemberships).innerJoin(users, eq(users.id, applicationMemberships.userId)).where(and(eq(applicationMemberships.applicationId, id), eq(applicationMemberships.status, 'active'))); for (const membership of memberships) { const assigned = await db.select().from(membershipRoles).innerJoin(roles, eq(roles.id, membershipRoles.roleId)).where(eq(membershipRoles.membershipId, membership.application_memberships.id)); for (const role of assigned) await this.keycloak.assignClientRole(membership.users.keycloakUserId, found.id, role.roles.code); } await this.audit(req, 'application.oauth_client.created', 'oauth_client', result[0].id, body); return result[0]; } catch (error) { if (localClientId) await db.delete(applicationOauthClients).where(eq(applicationOauthClients.id, localClientId)).catch(() => undefined); await this.keycloak.deleteClient(found.id).catch(() => undefined); throw error; } }
  @Patch(':id/oauth-clients/:clientId') async updateClient(@Param('id') id: string, @Param('clientId') clientId: string, @Body() body: OAuthClientUpdateDto, @Req() req: any) { await this.assertManageAccess(id, req); const row = (await db.select().from(applicationOauthClients).where(and(eq(applicationOauthClients.id, clientId), eq(applicationOauthClients.applicationId, id))))[0]; if (!row) throw new NotFoundException('OAuth client not found'); const kcUpdate: any = {}; for (const key of ['name', 'enabled', 'redirectUris', 'webOrigins']) if ((body as any)[key] !== undefined) kcUpdate[key] = (body as any)[key]; await this.keycloak.updateClient(row.keycloakClientUuid, kcUpdate); const saved = (await db.update(applicationOauthClients).set({ ...kcUpdate, updatedAt: new Date() } as any).where(eq(applicationOauthClients.id, clientId)).returning())[0]; await this.audit(req, 'application.oauth_client.updated', 'oauth_client', clientId, body); return saved; }
  @Delete(':id/oauth-clients/:clientId') async deleteClient(@Param('id') id: string, @Param('clientId') clientId: string, @Req() req: any) { await this.assertManageAccess(id, req); const row = (await db.select().from(applicationOauthClients).where(and(eq(applicationOauthClients.id, clientId), eq(applicationOauthClients.applicationId, id))))[0]; if (!row) throw new NotFoundException('OAuth client not found'); await this.keycloak.deleteClient(row.keycloakClientUuid); await db.delete(applicationOauthClients).where(eq(applicationOauthClients.id, clientId)); await this.audit(req, 'application.oauth_client.deleted', 'oauth_client', clientId); return { deleted: true }; }
  @Post(':id/oauth-clients/:clientId/rotate-secret') async rotateClientSecret(@Param('id') id: string, @Param('clientId') clientId: string, @Req() req: any) { await this.assertManageAccess(id, req); const row = (await db.select().from(applicationOauthClients).where(and(eq(applicationOauthClients.id, clientId), eq(applicationOauthClients.applicationId, id))))[0]; if (!row) throw new NotFoundException('OAuth client not found'); const secret: any = await this.keycloak.rotateClientSecret(row.keycloakClientUuid); await this.audit(req, 'application.oauth_client.secret_rotated', 'oauth_client', clientId); return { clientId: row.clientId, secret: secret.value }; }
  @Get(':id/admins') @UseGuards(PlatformAdminGuard) async adminList(@Param('id') id: string) { await this.assertApplication(id); return db.select({ userId: users.id, username: users.username, displayName: users.displayName, email: users.email, createdAt: applicationAdmins.createdAt }).from(applicationAdmins).innerJoin(users, eq(users.id, applicationAdmins.userId)).where(eq(applicationAdmins.applicationId, id)); }
  @Post(':id/admins') @UseGuards(PlatformAdminGuard) async addAdmin(@Param('id') id: string, @Body() body: AssignmentDto, @Req() req: any) { await this.assertApplication(id); const user = (await db.select().from(users).where(eq(users.id, body.id)))[0]; if (!user) throw new BadRequestException('User not found'); await db.insert(applicationAdmins).values({ applicationId: id, userId: body.id }).onConflictDoNothing(); await this.audit(req, 'assign', 'application_admin', `${id}:${body.id}`); return { assigned: true }; }
  @Delete(':id/admins/:userId') @UseGuards(PlatformAdminGuard) async removeAdmin(@Param('id') id: string, @Param('userId') userId: string, @Req() req: any) { await db.delete(applicationAdmins).where(and(eq(applicationAdmins.applicationId, id), eq(applicationAdmins.userId, userId))); await this.audit(req, 'unassign', 'application_admin', `${id}:${userId}`); return { deleted: true }; }
}
