import { and, eq } from 'drizzle-orm';
import { db, migrate, pool } from './db/database';
import { applicationMemberships, applications, applicationOauthClients, membershipRoles, permissions, rolePermissions, roles, users } from './db/schema';

const base = process.env.OIDC_INTERNAL_ISSUER || 'http://keycloak:8080/realms/pondok';
const adminBase = base.replace(/\/realms\/[^/]+$/, '/admin$&');
const adminClient = process.env.KEYCLOAK_ADMIN_CLIENT_ID || 'account-management-service';
const adminSecret = process.env.KEYCLOAK_ADMIN_CLIENT_SECRET || process.env.MANAGEMENT_CLIENT_SECRET;
const seedUsername = process.env.SEED_USERNAME || 'seed-browser-user';
const seedPassword = process.env.SEED_PASSWORD || 'SeedBrowserUser@1234';
const appCode = process.env.SEED_APPLICATION_CODE || 'seed-browser-app';
const clientId = process.env.SEED_CLIENT_ID || 'seed-browser-web';

if (process.env.NODE_ENV === 'production') throw new Error('Seeding is disabled in production');
if (!adminSecret) throw new Error('KEYCLOAK_ADMIN_CLIENT_SECRET or MANAGEMENT_CLIENT_SECRET is required');

async function kc(path: string, init: RequestInit = {}) {
  const response = await fetch(`${adminBase}${path}`, init);
  if (!response.ok && response.status !== 404) throw new Error(`Keycloak ${init.method || 'GET'} ${path} failed: ${response.status} ${await response.text()}`);
  return response.status === 204 ? undefined : response.json();
}

async function token() {
  const response = await fetch(`${base}/protocol/openid-connect/token`, { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ grant_type: 'client_credentials', client_id: adminClient, client_secret: adminSecret! }) });
  if (!response.ok) throw new Error(`Keycloak token request failed: ${response.status}`);
  return (await response.json()).access_token as string;
}

async function main() {
  await migrate();
  const accessToken = await token();
  const headers = { authorization: `Bearer ${accessToken}`, 'content-type': 'application/json' };
  const findSeedUser = async () => {
    const result = await kc(`/users?search=${encodeURIComponent(seedUsername)}&max=100`, { headers });
    if (!Array.isArray(result)) throw new Error(`Unexpected Keycloak users response: ${JSON.stringify(result)}`);
    return result.find((user) => user.username === seedUsername);
  };
  const foundUsers = await kc(`/users?search=${encodeURIComponent(seedUsername)}&max=100`, { headers });
  if (!Array.isArray(foundUsers)) throw new Error(`Unexpected Keycloak users response: ${JSON.stringify(foundUsers)}`);
  let keycloakUser = foundUsers.find((user) => user.username === seedUsername);
  if (!keycloakUser) {
    await kc('/users', { method: 'POST', headers, body: JSON.stringify({ username: seedUsername, email: `${seedUsername}@example.test`, firstName: 'Seed', lastName: 'Browser User', enabled: true, emailVerified: true }) });
    keycloakUser = await findSeedUser();
  }
  if (!keycloakUser?.id) throw new Error(`Unable to locate seeded Keycloak user '${seedUsername}'`);
  await kc(`/users/${keycloakUser.id}/reset-password`, { method: 'PUT', headers, body: JSON.stringify({ type: 'password', value: seedPassword, temporary: false }) });

  let localUser = (await db.select().from(users).where(eq(users.keycloakUserId, keycloakUser.id)))[0];
  if (!localUser) localUser = (await db.insert(users).values({ keycloakUserId: keycloakUser.id, username: seedUsername, displayName: 'Seed Browser User', email: `${seedUsername}@example.test`, status: 'active' }).returning())[0];

  let application = (await db.select().from(applications).where(eq(applications.code, appCode)))[0];
  if (!application) application = (await db.insert(applications).values({ code: appCode, name: 'Seed Browser Application', description: 'Generated by the safe browser test seed command' }).returning())[0];
  let role = (await db.select().from(roles).where(and(eq(roles.applicationId, application.id), eq(roles.code, 'seed-reader'))))[0];
  if (!role) role = (await db.insert(roles).values({ applicationId: application.id, code: 'seed-reader', name: 'Seed Reader', description: 'Seed role for browser testing' }).returning())[0];
  let permission = (await db.select().from(permissions).where(and(eq(permissions.applicationId, application.id), eq(permissions.code, 'seed-read'))))[0];
  if (!permission) permission = (await db.insert(permissions).values({ applicationId: application.id, code: 'seed-read', name: 'Seed Read', description: 'Seed permission for browser testing' }).returning())[0];
  await db.insert(rolePermissions).values({ roleId: role.id, permissionId: permission.id }).onConflictDoNothing();
  let membership = (await db.select().from(applicationMemberships).where(and(eq(applicationMemberships.applicationId, application.id), eq(applicationMemberships.userId, localUser.id))))[0];
  if (!membership) membership = (await db.insert(applicationMemberships).values({ applicationId: application.id, userId: localUser.id, status: 'active' }).returning())[0];
  await db.insert(membershipRoles).values({ membershipId: membership.id, roleId: role.id, assignedBy: localUser.id }).onConflictDoNothing();

  let client = (await db.select().from(applicationOauthClients).where(eq(applicationOauthClients.clientId, clientId)))[0];
  if (!client) {
    const clients = await kc(`/clients?clientId=${encodeURIComponent(clientId)}`, { headers }) as any[];
    const kcClient = clients[0] || await (async () => { await kc('/clients', { method: 'POST', headers, body: JSON.stringify({ clientId, name: 'Seed Browser Web Client', protocol: 'openid-connect', publicClient: true, standardFlowEnabled: true, directAccessGrantsEnabled: false, redirectUris: ['http://localhost:5173/auth/callback'], webOrigins: ['http://localhost:5173'] }) }); return (await kc(`/clients?clientId=${encodeURIComponent(clientId)}`, { headers }) as any[])[0]; })();
    client = (await db.insert(applicationOauthClients).values({ applicationId: application.id, keycloakClientUuid: kcClient.id, clientId, clientType: 'web', name: 'Seed Browser Web Client', redirectUris: ['http://localhost:5173/auth/callback'], webOrigins: ['http://localhost:5173'] }).returning())[0];
  }
  console.log(JSON.stringify({ username: seedUsername, applicationCode: appCode, clientId, role: role.code, permission: permission.code }, null, 2));
}

main().catch((error) => { console.error(error); process.exitCode = 1; }).finally(() => pool.end());
