import { boolean, jsonb, pgTable, text, timestamp, uuid, primaryKey, unique } from 'drizzle-orm/pg-core';

const id = () => uuid('id').defaultRandom().primaryKey();
const audit = { createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull() };

export const users = pgTable('users', { id: id(), keycloakUserId: text('keycloak_user_id').notNull().unique(), username: text('username').notNull(), displayName: text('display_name'), email: text('email'), phone: text('phone'), status: text('status').default('active').notNull(), ...audit });
export const applications = pgTable('applications', { id: id(), code: text('code').notNull().unique(), name: text('name').notNull(), description: text('description'), status: text('status').default('active').notNull(), ...audit });
export const applicationOauthClients = pgTable('application_oauth_clients', { id: id(), applicationId: uuid('application_id').notNull().references(() => applications.id, { onDelete: 'cascade' }), keycloakClientUuid: text('keycloak_client_uuid').notNull().unique(), clientId: text('client_id').notNull().unique(), clientType: text('client_type').notNull(), name: text('name').notNull(), enabled: boolean('enabled').default(true).notNull(), redirectUris: jsonb('redirect_uris').default([]).notNull(), webOrigins: jsonb('web_origins').default([]).notNull(), ...audit });
export const applicationMemberships = pgTable('application_memberships', { id: id(), applicationId: uuid('application_id').notNull().references(() => applications.id, { onDelete: 'cascade' }), userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), status: text('status').default('active').notNull(), ...audit }, (t) => [unique().on(t.applicationId, t.userId)]);
export const roles = pgTable('roles', { id: id(), applicationId: uuid('application_id').notNull().references(() => applications.id, { onDelete: 'cascade' }), code: text('code').notNull(), name: text('name').notNull(), description: text('description'), ...audit }, (t) => [unique().on(t.applicationId, t.code)]);
export const permissions = pgTable('permissions', { id: id(), applicationId: uuid('application_id').notNull().references(() => applications.id, { onDelete: 'cascade' }), code: text('code').notNull(), name: text('name').notNull(), description: text('description'), ...audit }, (t) => [unique().on(t.applicationId, t.code)]);
export const rolePermissions = pgTable('role_permissions', { roleId: uuid('role_id').notNull().references(() => roles.id, { onDelete: 'cascade' }), permissionId: uuid('permission_id').notNull().references(() => permissions.id, { onDelete: 'cascade' }) }, (t) => [primaryKey({ columns: [t.roleId, t.permissionId] })]);
export const membershipRoles = pgTable('membership_roles', { membershipId: uuid('membership_id').notNull().references(() => applicationMemberships.id, { onDelete: 'cascade' }), roleId: uuid('role_id').notNull().references(() => roles.id, { onDelete: 'cascade' }), assignedBy: uuid('assigned_by').references(() => users.id, { onDelete: 'set null' }), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() }, (t) => [primaryKey({ columns: [t.membershipId, t.roleId] })]);
export const applicationAdmins = pgTable('application_admins', { applicationId: uuid('application_id').notNull().references(() => applications.id, { onDelete: 'cascade' }), userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() }, (t) => [primaryKey({ columns: [t.applicationId, t.userId] })]);
export const auditLogs = pgTable('audit_logs', { id: id(), actorUserId: uuid('actor_user_id').references(() => users.id, { onDelete: 'set null' }), action: text('action').notNull(), entityType: text('entity_type').notNull(), entityId: text('entity_id'), metadata: jsonb('metadata').default({}).notNull(), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() });
